### ISSUE TITLE
Subscribing and Publishing to custom uORB topics with ROS2

### ISSUE THREAD

**Issue by karishmapatnaik** [PX4/px4_msgs#8] opened 2021-06-18 17:39 UTC
Hi,
I created a custom uORB topic in the px4 firmware and am trying to subscribe to this topic via ROS2. I changed the px4_msgs folder to include the new msg. However, the cmakelists doesn't automatically generate the required hpp file, can someone point me in the right direction? I created all the necessary files for publishing and serialization in the px4_ros_com package under src -> micrortps_agent. I tried to follow the similar steps to creation of a listener and included the "<newtopic>.hpp file for the script and it throws a fatal error saying there i sno such file or directory.

**Comment by TSC21** [comment] 2021-06-18 17:50
Mostly a duplicate of https://github.com/PX4/px4_msgs/issues/7. Please follow the answer to this there. Closing

**Closed by TSC21** 2021-06-18 17:50 UTC
